u6
u6

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,16 +23,16 @@ jobs:
          echo Adding GHS compiler to PATH...
          set PATH=D:\ghs\comp_202014;%PATH% 
          echo PATH after: %PATH%
-   Verify Compiler:    
-      # Stage 3: Verify Compiler
-    name: Set up GHS compiler path
-    runs-on: windows-latest
-    steps:
-      - name: Verify GHS compiler
-        shell: cmd
-        run: |
-          where ccthumb.exe
-          ccthumb.exe -version || echo "GHS compiler not found!"
+   #Verify Compiler:    
+   #   # Stage 3: Verify Compiler
+   # name: Set up GHS compiler path
+   # runs-on: windows-latest
+   # steps:
+   #   - name: Verify GHS compiler
+   #     shell: cmd
+   #     run: |
+   #       where ccthumb.exe
+   #       ccthumb.exe -version || echo "GHS compiler not found!"
     build:
     # Step 4: Build with Bazel
     name: build Stage
