u7
u7

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,8 +12,8 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-  compilercheck:
-    # Step 2: Add GHS compiler to PATHs
+  compilerpathcheck:
+    # Step 2: Add GHS compiler to PATH
     name: Set up GHS compiler path
     runs-on: windows-latest
     steps:
@@ -23,18 +23,18 @@ jobs:
          echo Adding GHS compiler to PATH...
          set PATH=D:\ghs\comp_202014;%PATH% 
          echo PATH after: %PATH%
-   #Verify Compiler:    
-   #   # Stage 3: Verify Compiler
-   # name: Set up GHS compiler path
-   # runs-on: windows-latest
-   # steps:
-   #   - name: Verify GHS compiler
-   #     shell: cmd
-   #     run: |
-   #       where ccthumb.exe
-   #       ccthumb.exe -version || echo "GHS compiler not found!"
-    build:
-    # Step 4: Build with Bazel
+  compilerexecheck:
+    # Stage 3: Verify Compiler
+    name: Set up GHS compiler path
+    runs-on: windows-latest
+    steps:
+      - name: Verify GHS compiler ccthumb.exe found or not
+        shell: cmd
+        run: |
+          where ccthumb.exe
+          ccthumb.exe -version || echo "GHS compiler not found!"
+  build:
+    # Step 3: Build with Bazel
     name: build Stage
     runs-on: windows-latest
     steps:
